[wallet/desktop] fix: symbol-sdk transaction info fixes in tests
symbol/desktop-wallet pull request #1924
Opened 2022-11-03 08:54 UTC by yilmazbahadir

## What was the issue?
After symbol-sdk@2.0.3 upgrade some of the unit tests began to fail due to the constructor signature change in TransactionInfo class.

## What's the fix?
Fixed the parameters need to be passed to TransactionInfo constructor.

2022-11-03 09:10 UTC, cryptoBeliever commented
@yilmazbahadir 
- when I run `npm run build` I got no test errors :heavy_check_mark: 
- when I run `npm run test` I got 4 tests failing (problem with localization):

![image](https://user-images.githubusercontent.com/17684281/199683170-250df942-df74-4c29-8fa6-821d2d29c697.png)

- I got also (when running npm run build) many Vue errors. Not sure if this is something to ignore or not.

2022-11-03 09:33 UTC, AnthonyLaw approved these changes
All good. 
IMO but instead of `undefined` we can just randomly mock the value.
because seems all mocking tx is confirmed. So `feeMultiplier` and `timestamp` should not `undefined`

2022-11-07 11:27 UTC, Jaguar0625 requested changes
> IMO but instead of undefined we can just randomly mock the value.
because since all mocking tx is confirmed. So feeMultiplier and timestamp should not undefined

I agree with @AnthonyLaw. Please update.

2022-11-07 13:19 UTC, yilmazbahadir commented
> > IMO but instead of undefined we can just randomly mock the value.
> > because since all mocking tx is confirmed. So feeMultiplier and timestamp should not undefined
> 
> I agree with @AnthonyLaw. Please update.

Updated with mock values.

2022-11-07 19:27 UTC, Jaguar0625 approved these changes

2022-11-07 20:20 UTC, merged